name: Update file(s) 
 
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "300 * * * *" # run every 5 hours
 
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
    - name: Format code
      run: black nepse_simple.py
 
    - name: Fetch data and update the file(s)
      run: python nepse_simple.py
 
    - name: Commit updated file(s) back to this repository
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "[skip ci] Save result of action"
          git fetch origin main
          git push origin main
 
    - name: Push file to rmeote repo
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        USERNAME: ${{ secrets.USERNAME }}
        EMAIL: ${{ secrets.EMAIL }}
        DEST_REPO: ${{ secrets.DEST_REPO }}
        DEST_FOLDER: ${{ secrets.DEST_FOLDER }}
      with:
        source_file: nepse_simple.xlsx
        destination_repo: "${USERNAME}/${DEST_REPO}"
        destination_folder: "${DEST_FOLDER}"
        user_name: "${USERNAME}"
        user_email: "${EMAIL}"
